/* ══════════════════════════════════════════════════════════════
   dict.js — 클릭 사전
   키는 소문자, 값은 "이 이야기 안에서의 뜻".
   원문에 실제로 나오는 낱말만 넣는다 (본문에 없는 키는 죽은 항목).
   불규칙 과거형은 원형을 괄호로 함께 보여 준다 — 한국인 학습자에게 가장 자주 걸리는 지점.
   ══════════════════════════════════════════════════════════════ */

window.MOC = window.MOC || {};

window.MOC.DICT = {

  /* ── 1–2쪽 · 오두막과 소원 ── */
  'once':'옛날에 (once upon a time = 옛날 옛적에)',
  'upon':'~위에 (once upon a time에서만 쓰는 옛말투)',
  'lived':'살았다 (live의 과거형)',
  'nice':'좋은, 아담한',
  'clean':'깨끗한',
  'around':'둘러싸고, 사방에',
  'except':'~을 빼고는',
  'flowers':'꽃',
  'couldn\'t':'~할 수 없었다 (could not)',
  'lonely':'외로운',
  'sighed':'한숨을 쉬었다',
  'fluffy':'폭신폭신한',
  'sweet':'귀여운, 다정한',
  'dear':'여보, 얘야 (다정하게 부르는 말)',

  /* ── 3쪽 · 길을 나서다 ── */
  'set':'나섰다 (set out = 길을 떠났다)',
  'hills':'언덕',
  'hill':'언덕',
  'climbed':'올랐다',
  'sunny':'햇살이 드는',
  'trudged':'터벅터벅 걸었다',
  'valleys':'골짜기',
  'cool':'서늘한',
  'walked':'걸었다',
  'came':'왔다, 다다랐다 (come의 과거형)',
  'quite':'아주, 완전히',
  'covered':'뒤덮인',
  'last':'마침내 (at last)',

  /* ── 4·12쪽 · 운율 ── */
  'kittens':'새끼 고양이',
  'kitten':'새끼 고양이',
  'everywhere':'어디에나',
  'hundreds':'수백',
  'thousands':'수천',
  'millions':'수백만',
  'billions':'수십억',
  'trillions':'수조',

  /* ── 5–6쪽 · 고르고 또 고르고 ── */
  'cried':'외쳤다 (cry의 과거형. 여기서는 "울었다"가 아니다)',
  'joyfully':'기쁘게',
  'choose':'고르다',
  'chose':'골랐다 (choose의 과거형)',
  'chosen':'골랐다 (choose의 과거분사)',
  'prettiest':'가장 예쁜',
  'pretty':'예쁜',
  'seemed':'~해 보였다',
  'also':'~도, 또한',
  'another':'또 다른 하나',
  'fuzzy':'보송보송한',
  'grey':'회색의',
  'corner':'구석',
  'lovely':'사랑스러운',
  'leave':'두고 가다, 남겨 두다',
  'shame':'아까운 일, 안타까운 일',
  'stripes':'줄무늬',
  'tiger':'호랑이',
  'simply':'그저, 정말로',
  'must':'꼭 ~해야 한다',
  'took':'데려갔다, 가져갔다 (take의 과거형)',

  /* ── 위치·때를 나타내는 까다로운 말 ── */
  'about':'막 ~하려는 참 (about to leave = 막 떠나려던 참에)',
  'just':'막, 바로 (just as he was about to leave)',
  'way':'저 멀리 (way over here = 저 멀리 이쪽에)',
  'others':'다른 것들',
  'back':'되돌아 (went back = 돌아갔다)',

  /* ── 7–8쪽 · 어느새 전부 ── */
  'happened':'일어났다, 그렇게 되었다',
  'looked':'보았다 (look up = 고개를 들었다)',
  'bear':'견디다, 참다 (동물 "곰"이 아니다)',
  'knew':'알았다 (know의 과거형)',
  'before':'~하기도 전에',
  'went':'갔다 (go의 과거형)',
  'through':'~을 통과해서',
  'show':'보여 주다',
  'funny':'우스운',
  'following':'뒤따라오는',

  /* ── 9–10쪽 · 연못과 풀 ── */
  'pond':'연못',
  'thirsty':'목마른',
  'mew':'야옹 (고양이 울음소리)',
  'well':'글쎄, 그런데 (문장 앞에서 뜸 들이는 말)',
  'great':'아주 큰 (a great deal = 아주 많은 양)',
  'deal':'양 (a great deal of = 아주 많은)',
  'each':'각각의, ~마다',
  'sip':'한 모금',
  'gone':'사라진',
  'hungry':'배고픈',
  'grass':'풀',
  'much':'많은',
  'ate':'먹었다 (eat의 과거형)',
  'mouthful':'한 입',
  'blade':'풀잎 한 장 (a blade of grass)',
  'left':'남았다 (leave의 과거분사)',

  /* ── 11쪽 · 마당에서 마주치다 ── */
  'soon':'곧 (pretty soon = 얼마 지나지 않아)',
  'saw':'보았다 (see의 과거형)',
  'coming':'오고 있는',
  'doing':'하고 있는',
  'asked':'부탁했다, 물었다',

  /* ── 13쪽 · 누가 제일 예쁘니 ── */
  'never':'결코 ~않다',
  'feed':'먹이다, 먹여 키우다',
  'eat':'먹다 (eat out of house and home = 살림을 거덜내다)',
  'home':'집, 살림',
  'thought':'생각했다 (think의 과거형)',
  'shall':'~할까요 (What shall we do? = 어떻게 하지?)',
  'while':'잠시 동안 (for a while)',
  'know':'알다',
  'let':'~하게 하다',
  'decide':'결정하다',
  'keep':'기르다, 계속 두다',
  'should':'~해야 한다',
  'called':'불렀다, 외쳤다',
  'voices':'목소리들',
  'itself':'그 자신',

  /* ── 14쪽 · 소란 ── */
  'began':'시작했다 (begin의 과거형)',
  'quarrel':'다투다',
  'quarreling':'다툼',
  'bit':'물었다 (bite의 과거형. "조금"이 아니다)',
  'scratched':'할퀴었다',
  'clawed':'발톱으로 할퀴었다',
  'other':'서로 (each other = 서로서로)',
  'made':'냈다, 만들었다 (make의 과거형)',
  'noise':'소리, 소음',
  'ran':'뛰었다 (run의 과거형)',
  'fast':'빠르게 (as fast as they could = 있는 힘껏)',
  'such':'그런, 그토록',
  'stopped':'그쳤다, 멈췄다',
  'peeped':'살짝 들여다보았다',
  'window':'창문',
  'happen':'일어나다',
  'single':'단 하나의',

  /* ── 15쪽 · 풀숲의 아기 고양이 ── */
  'eaten':'먹혔다, 먹어 치웠다 (eat의 과거분사)',
  'too':'너무, ~도 (It\'s too bad! = 안됐구나!)',
  'bad':'안된, 나쁜',
  'pointed':'가리켰다',
  'bunch':'덤불, 무더기',
  'high':'키가 큰, 높은',
  'sat':'앉아 있었다 (sit의 과거형)',
  'little':'작은, 어린',
  'frightened':'겁먹은',
  'picked':'집어 들었다 (pick up)',
  'thin':'야윈, 마른',
  'scraggly':'볼품없는, 삐쭉삐쭉한',
  'kitty':'아가야, 야옹아 (고양이를 다정하게 부르는 말)',
  'homely':'못생긴, 수수한',
  'anything':'아무것도',
  'nobody':'아무도 ~않다',
  'bothered':'신경 썼다',

  /* ── 16쪽 · 세상에서 제일 아름다운 고양이 ── */
  'into':'~안으로',
  'gave':'주었다 (give의 과거형)',
  'warm':'따뜻한',
  'bath':'목욕',
  'brushed':'빗질했다',
  'fur':'털',
  'until':'~할 때까지',
  'soft':'부드러운',
  'shiny':'반질반질한',
  'plenty':'듬뿍, 충분히',
  'milk':'우유',
  'grew':'자랐다 (grow의 과거형)',
  'plump':'통통한',
  'after':'그러고 보니 (after all = 결국, 알고 보니)',
  'beautiful':'아름다운',
  'whole':'전체의, 온',
  'world':'세상',
  'ought':'~해야 마땅하다 (I ought to know = 내가 잘 알지)',
  'seen':'보았다 (see의 과거분사)',
  'found':'발견했다 (find의 과거형)',
  'black':'검은',
  'white':'흰',
  'brown':'갈색의',
  'yellow':'노란',
  'baby':'아기',
  'water':'물',
  'house':'집',
  'door':'문',
  'woman':'여자, 할머니',
  'man':'남자, 할아버지',
  'old':'나이 많은, 오래된',
  'very':'아주',
  'said':'말했다 (say의 과거형)',
  'i\'m':'나는 ~이다 (I am)',
  'i\'ve':'나는 ~했다 (I have)',
  'didn\'t':'~하지 않았다 (did not)',
  'it\'s':'그것은 ~이다 (it is)'
};
